### ISSUE TITLE
Notice: github profile page readme

### ISSUE THREAD

**Issue by MichaelDimmitt** [robmcguinness/robmcguinness#3]
your repo, 
"is now a special repository."

You can display the README of this repository on your public GitHub profile.

and have your profile page look like this guys:

https://github.com/MikeMcQuaid

I mention because I forked your project a while back.

Obligatory image if you recreated the repo from scratch starting today:
![Screen Shot 2020-09-24 at 6 09 45 PM](https://user-images.githubusercontent.com/11463275/94205639-afb7e900-fe91-11ea-87ab-b8cc2f842c15.png)

my profile also has the smiley readme: 
https://github.com/MichaelDimmitt

**Comment by MichaelDimmitt** [comment]
Additionally you would see a button to publish your repo here:

![Screen Shot 2020-09-24 at 6 58 57 PM](https://user-images.githubusercontent.com/11463275/94208910-f1985d80-fe98-11ea-89e6-408177663d63.png)

## Feel Free to close if this is of no interest to yourself. 🙂

**Comment by robmcguinness** [comment]
Thanks! I'll have to update my Github profile shortly.
